# Generated by Django 5.0.1 on 2024-01-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
