# Generated by Django 5.0.1 on 2024-01-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='status',
            field=models.CharField(default='finished', max_length=20),
        ),
    ]
