# Generated by Django 5.0.1 on 2024-01-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_alter_gamesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='mode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
