# Generated by Django 5.0.1 on 2024-02-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_gamesession_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('local', 'Local'), ('tournament', 'Tournament')], default='online', max_length=15),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('finished', 'Finished')], default='pending', max_length=15),
        ),
    ]
