# Generated by Django 5.0.4 on 2024-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0007_gamesession_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
