services:
  website:
    build: website
    env_file:
      - .env
    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    depends_on:
        - db

  db:
    build: ./postgreSQL
    env_file:
      - .env
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    build: nginx
    ports:
        - '8080:80'
        - '8443:443'
    env_file:
        - .env
    environment:
        - PRIVATE_KEY=${CERTIFICATE_KEY}
    depends_on:
        - website
