version: '3.8'
services:
  website:
    build: website
    volumes:
      - ./website/django_project:/website
    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./postgreSQL/data:/var/lib/postgresql/data

  nginx:
    build: nginx
    ports:
        - '8080:80'
        - '8443:443'
    depends_on:
        - website

    command: /bin/bash -c "rm -f /etc/nginx/sites-enabled/default &&
                            rm -f /etc/nginx/sites-available/default && nginx -g 'daemon off;'"
                    