version: '3'
services:
  web:
    image: python:latest
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "pip install --upgrade pip && pip install -r requirements.txt && sleep infinity"
    ports:
      - "8080:8080"
