version: '3'
services:
  website:
    build: website
    volumes:
      - ./website/django_project:/website
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - website
    command: /bin/bash -c "rm -f /etc/nginx/sites-enabled/default && 
              rm -f /etc/nginx/sites-available/default && nginx -g 'daemon off;'"