version: '3.9'
services:
  website:
    build: website
    volumes:
      - ./website/django_project:/website
    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000"
    expose:
      - 8000
    depends_on:
        - db

  db:
    build: postgreSQL

  nginx:
    build: nginx
    ports:
        - '8080:80'
        - '8443:443'
    depends_on:
        - website

    command: /bin/bash -c "rm -f /etc/nginx/sites-enabled/default &&
                            rm -f /etc/nginx/sites-available/default && nginx -g 'daemon off;'"
                    