# Generated by Django 5.0.1 on 2024-01-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldUser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tournament_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
