# Generated by Django 5.0.4 on 2024-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_olduser_customuser_tournament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hello',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
