# Generated by Django 5.0.4 on 2024-04-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hello',
        ),
    ]
