# Generated by Django 5.0.6 on 2024-05-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
