# Generated by Django 5.0.6 on 2024-05-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
