# Generated by Django 5.0.1 on 2024-01-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=15),
        ),
    ]
