# Generated by Django 5.0.1 on 2024-02-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_tournament_name_tournamentround_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='size',
            field=models.IntegerField(default=8),
        ),
    ]
