# Generated by Django 5.0.1 on 2024-02-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_remove_tournamentmatch_player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmatch',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('scheduled', 'Scheduled'), ('in progress', 'In Progress'), ('completed', 'Completed')], default='created', max_length=20),
        ),
    ]
