# Generated by Django 5.0.1 on 2024-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_tournamentmatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
