# Generated by Django 5.0.6 on 2024-05-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournament_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='tournament_nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
