# Generated by Django 5.0.6 on 2024-05-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournamentparticipant_tournament_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipant',
            name='tournament_nickname',
        ),
    ]
